### ISSUE TITLE
测试模型结果 成功率不行

### ISSUE THREAD

**Issue by qing-shang** [Yakuho/ReadItEasy#1]

**Comment by Yakuho** [comment]
暂时没有pytorch版本，该网络改成pytorch版的还是比较轻松的

**Comment by qingshangi** [comment]
> 

那可以改下吗

**Comment by qing-shang** [comment]
> 暂时没有pytorch版本，该网络改成pytorch版的还是比较轻松的

自带的模型测试识别率11个能成功两， cpu训练出来的结果，也不太理想 是否要gpu才行呢

**Comment by Yakuho** [comment]
自带的模型如果对您当前的“字体”识别不理想，可以参考文档训练一个您当前“字体”的私有化模型，一般训练出来都是比较理想的。在字体识别任务中，一般使用几个woff文件作为训练集就能达到不错的效果。

**Comment by qing-shang** [comment]
> 自带的模型如果对您当前的“字体”识别不理想，可以参考文档训练一个您当前“字体”的私有化模型，一般训练出来都是比较理想的。在字体识别任务中，一般使用几个woff文件作为训练集就能达到不错的效果。

自带的MAYan.h5模型，预测test.woff MaYan.001.woff, 不理想

**Comment by Yakuho** [comment]
> 

一般情况下，例如MaoYan站的字体文件，只能适配于MaoYan站系列的字体文件，不能适配其他站例如DaZhongDianPing等字体文件，所以建议训练一个私有化的

**Comment by qing-shang** [comment]
> > 
> 
> 
> 
> 一般情况下，例如MaoYan站的字体文件，只能适配于MaoYan站系列的字体文件，不能适配其他站例如DaZhongDianPing等字体文件，所以建议训练一个私有化的

晚点给你预测结果，用着MaoYan测试不理想
